services:
  vulnerable_mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_vulnerable
    volumes:
      - ./vulnerable/db.sql:/docker-entrypoint-initdb.d/db.sql

  secure_mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_secure
    volumes:
      - ./secure/db.sql:/docker-entrypoint-initdb.d/db.sql

  vulnerable_php_app:
    build:
      context: .  # Use the current directory
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./vulnerable:/var/www/html
    depends_on:
      - vulnerable_mysql
    environment:
      MYSQL_HOST: vulnerable_mysql
      MYSQL_DATABASE: ecommerce_vulnerable
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  secure_php_app:
    build:
      context: .  # Use the same Dockerfile for secure
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./secure:/var/www/html
    depends_on:
      - secure_mysql
    environment:
      MYSQL_HOST: secure_mysql
      MYSQL_DATABASE: ecommerce_secure
      MYSQL_USER: root
      MYSQL_PASSWORD: root
