version: '3.8'

services:
  php_vulnerable:
    build: .
    platform: linux/amd64  # Force x86_64 architecture
    container_name: vulnerable_php_app
    ports:
      - "8080:80"
    volumes:
      - ./vulnerable:/var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  php_secure:
    build: .
    platform: linux/amd64  # Force x86_64 architecture
    container_name: secure_php_app
    ports:
      - "8081:80"  # Exposing a different port for secure pages
    volumes:
      - ./secure:/var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  mysql:
    image: mysql:5.7
    container_name: vulnerable_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql_data: